### ISSUE TITLE
ICP v3.1 support

### ISSUE THREAD

**Issue by darcy202** [ibm-cloud-architecture/terraform-icp-aws#4]
Any necessary updates to support ICP v3.1

**Comment by darcy202** [comment]
Initial attempt to run with v3.1 binary failed with:

```
included: /installer/playbook/roles/icp-registry-image/tasks/offline-package-images.yaml for <IP address>

TASK [icp-registry-image : Checking offline image package] *********************
changed: [<IP address> -> localhost]

TASK [icp-registry-image : Aborting installation process] **********************
fatal: [<IP address>]: FAILED! => changed=false
  msg: Unable to find offline package under images directory
```

**Comment by darcy202** [comment]
Manually loaded cluster/images/ibm-cloud-private-x86_64-3.1.0.tar.gz and reran ```
ibmcom/icp-inception-ARCH:3.1.0-ee install
```

Which fell down trying to build multiarch image:

```
TASK [icp-registry-image-push : Building multiarch images] *************************************************************************************************************************************************
FAILED - RETRYING: Building multiarch images (3 retries left).
FAILED - RETRYING: Building multiarch images (2 retries left).
FAILED - RETRYING: Building multiarch images (1 retries left).
fatal: [<IP address> -> <IP address>]: FAILED! => changed=true
  attempts: 3
  cmd: |-
    export NO_PROXY=<ICP console>.elb.eu-west-1.amazonaws.com:8500
     rc=0
     for image in $(cat /tmp/image-registry/image-list.txt | sort -u); do
     manifest-tool push from-args --platforms linux/amd64,linux/ppc64le,linux/s390x --template <ICP console>.elb.eu-west-1.amazonaws.com:8500/ibmcom/${image//:/-ARCH:} --target <ICP console>.elb.eu-west-1.amazonaws.com:8500/ibmcom/$image --ignore-missing
     if [[ $? -ne 0 ]] && [[ ! "$image" =~ (icp-helm-api|icp-helm-rudder|icp-cert-gen) ]]; then
     echo "Build multiarch image failed for $image"
     rc=1
     fi
     done
     exit $rc
  delta: '0:00:00.073278'
  end: '2018-09-15 08:05:36.437997'
  msg: non-zero return code
  rc: 1
  start: '2018-09-15 08:05:36.364719'
  stderr: |-
```

**Comment by osowski** [comment]
@darcy202 We have the latest working on AWS and ICP 3.1 available in my dev fork at https://github.com/osowski/terraform-icp-aws.  We are actively discussing how we will approach integrating these changes into the main repository and whether that will be via a branch or multi-version support in `master`.   Please have a look at the updates and let us know if you have any success or issues with them.

**Comment by osowski** [comment]
Current as of https://github.com/ibm-cloud-architecture/terraform-icp-aws/commit/8ea9ed4ef7ab453cf29571701a093a3eaeb22688
